apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cedricclyburn-demo-poi-gateway-app-dev
  annotations:
    argocd/app-name: cedricclyburn-demo-poi-gateway-app-dev
    backstage.io/kubernetes-id: cedricclyburn-demo-poi-gateway-app
    backstage.io/kubernetes-namespace: cedricclyburn-demo
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh-gh/cedricclyburn-demo-gateway
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - java
    - quarkus
    - maven
    - workshop
  links:
    - url: https://console-openshift-console.apps.rosa-x4jc7.l07n.p1.openshiftapps.com/dev-pipelines/ns/cedricclyburn-demo/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.rosa-x4jc7.l07n.p1.openshiftapps.com/k8s/ns/cedricclyburn-demo/deployments/cedricclyburn-demo-poi-gateway-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.rosa-x4jc7.l07n.p1.openshiftapps.com/#https://github.com/rhdh-gh/cedricclyburn-demo-gateway?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/cedricclyburn"
  system: workshop-system-cedricclyburn-demo
  providesApis:
    - gateway-api-cedricclyburn-demo
  consumesApis:
    - backend-api-cedricclyburn-demo
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-cedricclyburn-demo
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/cedricclyburn"
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: gateway-api-cedricclyburn-demo
  description: API surface exposed to interact with Backends (summit POIs + parks data) via the Gateway
  links:
    - url: http://cedricclyburn-demo-poi-gateway-app-cedricclyburn-demo.apps.rosa-x4jc7.l07n.p1.openshiftapps.com/q/swagger-ui
      title: Swagger UI
      icon: web
    - url: https://github.com/rhdh-gh/cedricclyburn-demo-gateway/tree/main/src/main/resources/META-INF/openapi.yaml
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: production
  owner: "user:default/cedricclyburn"
  system: workshop-system-cedricclyburn-demo
  definition:
    $text: https://github.com/rhdh-gh/cedricclyburn-demo-gateway/tree/main/src/main/resources/META-INF/openapi.yaml
